version: "3.7"
services:
  app:
    container_name: adonis_app
    # restart: always
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
    image: adonisapp-dev:1.0
    volumes:
      - ../:/src
      - node_modules:/src/node_modules
    ports:
      - 3333:3333

  db:
    container_name: adonis_postgres
    image: postgres:12-alpine
    ports:
      - 54321:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db:/var/lib/postgresql/data

# named volumes is handled by docker.
volumes:
#   db_data:
  node_modules:
